spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uket?useSSL=false&allowPublicKeyRetrieval=true
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 40
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  token:
    secret-key: testestsetsetsetsetsetsetsetsetestset
    expiration:
      access-token-expiration: 600_000
      refresh-token-expiration: 7_200_000
